In [1]:
import pandas as pd

In [2]:
df_AlbaranesFiltradoML = pd.read_csv('AlbaranesFiltrado.csv')

In [3]:
df_AlbaranesFiltradoML.head()

,CodigoCliente,NumeroAlbaran,CodigoArticulo,CodigoAlmacen,Unidades,Precio,ImporteBruto,ImporteNeto,BaseImponible,MargenBeneficio,Almacen,TipoTransaccion,FechaAlbaran,MargenBeneficiounitario,CodigoCanal
0,11476,8593,935-640,0,10,23.099,230.99,133.05,131.7195,92.24,Cordoba,Compra,2024-3-12,9.224000,Cruz3
1,11476,8593,932-014,0,10,12.355,123.55,71.16,70.4484,57.53,Cordoba,Compra,2024-3-12,5.753000,Cruz3
2,11476,8593,925-785,0,10,144.587,1445.87,832.82,824.4918,512.74,Cordoba,Compra,2024-3-12,51.274000,Cruz3
3,11476,23224,940-015,0,8,33.750,270.00,270.00,267.3000,83.75,Cordoba,Compra,2024-6-25,10.468750,Cruz3
4,11476,41908,940-400,0,6,3.250,19.50,19.50,19.3050,10.69,Cordoba,Compra,2022-11-11,1.781667,Cruz3

In [4]:
len(df_AlbaranesFiltradoML)

635414

## Filtramos por Portabicibletas

In [6]:
# Lista de códigos a filtrar (portabicibletas)
codigos = [
    "952-295", "952-432", "952-084", "952-086", "952-087", "940-506AU", "940-511AU", "940-515AU", "952-019", "952-022", "952-023", "952-026", "952-028", "952-051", "952-052", "940-001", "940-005", "940-010", "940-506", "940-508", "940-511", "940-515", "940-520", "940-525", "940-006", "940-007", "940-544", "940-563", "940-564", "940-565", "940-012", "940-015", "940-016", "940-541", "940-560", "940-561", "940-562", "R130101001"]
# Filtramos el DataFrame
df_AlbaranesFiltradoML_filtrado1 = df_AlbaranesFiltradoML[df_AlbaranesFiltradoML["CodigoArticulo"].isin(codigos)]

In [7]:
len(df_AlbaranesFiltradoML_filtrado1)

11050

## Filtramos por años a partir de 2021

In [9]:
# Convertimos la columna a datetime (asumiendo formato día/mes/año)
df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"] = pd.to_datetime(df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"], dayfirst=True)

# Definimos la fecha límite
fecha_limite = pd.to_datetime("31/12/2020", dayfirst=True)

# Filtramos el DataFrame
df_AlbaranesFiltradoML_filtrado2 = df_AlbaranesFiltradoML_filtrado1[df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"] > fecha_limite]

C:\Users\gemav\AppData\Local\Temp\ipykernel_23400\2435649614.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"] = pd.to_datetime(df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"], dayfirst=True)
C:\Users\gemav\AppData\Local\Temp\ipykernel_23400\2435649614.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"] = pd.to_datetime(df_AlbaranesFiltradoML_filtrado1["FechaAlbaran"], dayfirst=True)

In [10]:
len(df_AlbaranesFiltradoML_filtrado2)

6587

### Analizamos cuantas lineas por tipo de canal tenemos para ver si Usuario Final es relevante en nuestro anlálisis o no

In [12]:
tabla_recuento = df_AlbaranesFiltradoML_filtrado2.groupby("CodigoCanal").size().reset_index(name="Recuento")
tabla_recuento

   CodigoCanal  Recuento
0        Cruz1       854
1        Cruz2      1190
2       Cruz2P       170
3       Cruz2W       616
4        Cruz3       301
5       Cruz3S       272
6       Cruz3W       137
7        Cruz4       130
8        Cruz5        85
9      CruzCON         3
10   CruzFLEET        34
11      CruzND      1462
12     CruzOEM        15
13     CruzSPO       522
14     CruzWEB       715
15   UsuarioCR        66
16   UsuarioRK        15

## Filtramos por Municipio (Madrid)

In [14]:
# Importamos el archivo Excel de Clientes 
df_Clientes = pd.read_excel("Clientes.xlsx")

In [15]:
df_Clientes.head()

,CodigoCliente,CodigoCanal,BajaEmpresaLc,FechaAlta,FechaBajaLc,CodigoMunicipio
0,60727,UsuarioCR,0,2024-05-28,NaT,8001
1,61028,UsuarioCR,0,2024-08-14,NaT,8001
2,60541,UsuarioCR,0,2024-03-12,NaT,8014
3,60321,UsuarioCR,0,2023-12-05,NaT,8015
4,60914,UsuarioCR,0,2024-07-15,NaT,8015

In [16]:
# Realizamos la unión (merge) usando 'left join' para conservar todos los registros del df_AlbaranesFiltradoML_filtrado2
df_AlbaranesFiltradoML_filtrado2 = df_AlbaranesFiltradoML_filtrado2.merge(df_Clientes[['CodigoCliente','CodigoMunicipio']], on='CodigoCliente', how='left')
df_AlbaranesFiltradoML_filtrado2.head()

,CodigoCliente,NumeroAlbaran,CodigoArticulo,CodigoAlmacen,Unidades,Precio,ImporteBruto,ImporteNeto,BaseImponible,MargenBeneficio,Almacen,TipoTransaccion,FechaAlbaran,MargenBeneficiounitario,CodigoCanal,CodigoMunicipio
0,11476,23224,940-015,0,8,33.75,270.00,270.00,267.3000,83.75,Cordoba,Compra,2024-06-25,10.468750,Cruz3,28079
1,11476,24712,940-015,0,4,33.75,135.00,135.00,133.6500,41.87,Cordoba,Compra,2024-07-02,10.467500,Cruz3,28079
2,11476,5276,940-015,0,3,33.75,101.25,101.25,100.2375,40.33,Cordoba,Compra,2024-02-14,13.443333,Cruz3,28079
3,11476,17985,940-015,0,3,33.75,101.25,101.25,100.2375,38.47,Cordoba,Compra,2023-05-31,12.823333,Cruz3,28079
4,11476,20922,940-015,0,2,33.75,67.50,67.50,66.8250,25.91,Cordoba,Compra,2023-06-20,12.955000,Cruz3,28079

In [17]:
len(df_AlbaranesFiltradoML_filtrado2)

6591

In [18]:
codigosMadrid = [
    28001, 28002, 28003, 28004, 28005, 28006, 28007, 28008, 28009,
    28010, 28011, 28012, 28013, 28014, 28015, 28016, 28017, 28018,
    28019, 28020, 28021, 28022, 28023, 28024, 28025, 28026, 28027,
    28028, 28029, 28030, 28031, 28032, 28033, 28034, 28035, 28036,
    28037, 28038, 28039, 28040, 28041, 28042, 28043, 28044, 28045,
    28046, 28047, 28048, 28049, 28050, 28051, 28052, 28053, 28054,
    28055, 28056, 28057, 28058, 28059, 28060, 28061, 28062, 28063,
    28064, 28065, 28066, 28067, 28068, 28069, 28070, 28071, 28072,
    28073, 28074, 28075, 28076, 28078, 28079, 28080, 28082, 28083,
    28084, 28085, 28086, 28087, 28088, 28089, 28090, 28091, 28092,
    28093, 28094, 28095, 28096, 28097, 28099, 28100, 28101, 28102,
    28104, 28106, 28107, 28108, 28109, 28110, 28111, 28112, 28113,
    28114, 28115, 28116, 28117, 28118, 28119, 28120, 28121, 28122,
    28123, 28124, 28125, 28126, 28127, 28128, 28129, 28130, 28131,
    28132, 28133, 28134, 28135, 28136, 28137, 28138, 28140, 28141,
    28143, 28144, 28145, 28146, 28147, 28148, 28149, 28150, 28151,
    28152, 28153, 28154, 28155, 28156, 28157, 28158, 28159, 28160,
    28161, 28162, 28163, 28164, 28165, 28166, 28167, 28168, 28169,
    28170, 28171, 28172, 28173, 28174, 28175, 28176, 28177, 28178,
    28179, 28180, 28181, 28182, 28183, 28901, 28902, 28903
   ]
# Filtramos el DataFrame
df_AlbaranesFiltradoML_filtrado3 = df_AlbaranesFiltradoML_filtrado2[df_AlbaranesFiltradoML_filtrado2["CodigoMunicipio"].isin(codigosMadrid)]

In [19]:
len(df_AlbaranesFiltradoML_filtrado3)

563

In [20]:
tabla_recuento2 = df_AlbaranesFiltradoML_filtrado3.groupby("CodigoCanal").size().reset_index(name="Recuento")
tabla_recuento2

   CodigoCanal  Recuento
0        Cruz1       127
1        Cruz2       102
2       Cruz2P         1
3        Cruz3        12
4        Cruz4         1
5    CruzFLEET         5
6       CruzND       243
7      CruzOEM        15
8      CruzSPO         5
9      CruzWEB        37
10   UsuarioCR        15

## Filtramos por CruzND

In [22]:
# Filtramos el DataFrame
df_AlbaranesFiltradoML_CruzND = df_AlbaranesFiltradoML_filtrado3[df_AlbaranesFiltradoML_filtrado3["CodigoCanal"].isin(["CruzND"])]

In [23]:
len(df_AlbaranesFiltradoML_CruzND)

243

In [47]:
df_AlbaranesFiltradoML_CruzND.head()

,CodigoCliente,NumeroAlbaran,CodigoArticulo,CodigoAlmacen,Unidades,Precio,ImporteBruto,ImporteNeto,BaseImponible,MargenBeneficio,Almacen,TipoTransaccion,FechaAlbaran,MargenBeneficiounitario,CodigoCanal,CodigoMunicipio
2219,17443,4825,940-010,0,2,29.00,58.0,58.0,58.0,24.60,Cordoba,Compra,2023-02-14,12.300,CruzND,28079
2220,17443,7084,940-010,0,2,29.00,58.0,58.0,58.0,24.60,Cordoba,Compra,2023-03-06,12.300,CruzND,28079
2221,17443,4826,940-001,0,2,18.25,36.5,36.5,36.5,16.42,Cordoba,Compra,2023-02-14,8.210,CruzND,28079
2222,17443,26091,940-005,0,2,20.75,41.5,41.5,41.5,18.11,Cordoba,Compra,2023-07-13,9.055,CruzND,28079
2223,17443,39206,940-005,0,2,20.75,41.5,41.5,41.5,18.11,Cordoba,Compra,2022-10-17,9.055,CruzND,28079

In [55]:
df_AlbaranesFiltradoML_CruzND2 = df_AlbaranesFiltradoML_CruzND.drop(columns=["CodigoCliente","NumeroAlbaran","CodigoAlmacen","Precio","ImporteBruto","ImporteNeto","BaseImponible","MargenBeneficio","Almacen","TipoTransaccion","MargenBeneficiounitario","CodigoCanal","CodigoMunicipio"])

In [57]:
df_AlbaranesFiltradoML_CruzND2.head()

     CodigoArticulo  Unidades FechaAlbaran
2219        940-010         2   2023-02-14
2220        940-010         2   2023-03-06
2221        940-001         2   2023-02-14
2222        940-005         2   2023-07-13
2223        940-005         2   2022-10-17

In [59]:
len(df_AlbaranesFiltradoML_CruzND2)

243

In [61]:
df_AlbaranesFiltradoML_CruzND2.to_excel("AlbaranesFiltradoML_CruzND.xlsx", index=False)